name = "Well Its Optimized"
author = "ZenXArch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bd2d2d999781b275f76b7a0d976fb36b219f2e922ef94dded1be4e387b9a1a8"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
