name = "Well Its Optimized"
author = "ZenXArch"
version = "1.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35fcd907991c619cf86f860df324f2feeb4a3527e09dae7dcf5d69b7092267c6"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
