name = "Well Its Optimized"
author = "ZenXArch"
version = "1.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abfcde62944a0d5346983487e12bea7df4d93359612553773c8df2001f78064d"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
