name = "Well Its Optimized"
author = "ZenXArch"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bc4c88a0373833be6d9c4f9a8ef9cba639ac24a7ebeb322d918990f6dc32c3b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
