name = "Well Its Optimized"
author = "ZenXArch"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a8856d656c9522eb36431fe23f32d88483276a07d5458cf9e13f6f0d5a63d92"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
