name = "Well Its Optimized"
author = "ZenXArch"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43a2d57d18b8336950a35561264137ea6708b0256272b557033cf6c3fd7ed81f"

[versions]
minecraft = "1.20.1"
quilt = "1.19.2"
