name = "Well It's Optimized"
author = "ZenXArch"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c81b3e011e4fe914064ad0e016c0ffd2e3eac9ed85db3fd328bb81c002fd2ff9"

[versions]
minecraft = "1.20.1"
quilt = "1.19.2"
