name = "Well Its Optimized"
author = "ZenXArch"
version = "1.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc4216404a59a41aea8fa78edd5f8589178c5c43fa8fd098eb0df0b78fd01d01"

[versions]
minecraft = "1.20.1"
quilt = "1.19.2"
