name = "Well Its Optimized"
author = "ZenXArch"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c467a8589b247b4454f0299a9d86c638241fcac7f35adfb44d37b90ebef117ef"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
