name = "Well Its Optimized"
author = "ZenXArch"
version = "1.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a941dd08b8bfe6f7e04b569d6999b6ccbbcef99059ded1aae4dc05cdfeb028e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
