name = "Zombie Apocalypse"
author = "ZenXArch"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e2051e4b932a2d45f970f4520f0e0f124d5d2e3384b4e87a225d7be06041619"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
